
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('locations').del()
    .then(function () {
      // Inserts seed entries
      return knex('locations').insert([
      {location_name:'Aland Islands', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Albania', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Andorra', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Armenia', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Austria', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Azerbaijan', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Belarus', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Belgium', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Bosnia and Herzegovina', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Bulgaria', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Croatia', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Cyprus', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Czech Republic', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Denmark', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Estonia', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Faroe Islands', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Finland', continent: 'Europe', type: 'country', data: ''},
      {location_name:'France', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Georgia', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Germany', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Gibraltar', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Greece', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Guernsey', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Hungary', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Iceland', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Ireland', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Isle of Man', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Italy', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Jersey', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Kosovo', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Latvia', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Liechtenstein', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Lithuania', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Luxembourg', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Macedonia', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Malta', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Moldova', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Monaco', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Montenegro', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Netherlands', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Norway', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Poland', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Portugal', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Romania', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Russia', continent: 'Europe', type: 'country', data: ''},
      {location_name:'San Marino', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Serbia', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Slovakia', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Slovenia', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Spain', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Svalbard and Jan Mayen', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Sweden', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Switzerland', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Turkey', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Ukraine', continent: 'Europe', type: 'country', data: ''},
      {location_name:'United Kingdom', continent: 'Europe', type: 'country', data: ''},
      {location_name:'Vatican City', continent: 'Europe', type: 'country', data: ''},

      {location_name:'Anguilla', continent: 'North America', type: 'country', data: ''},
      {location_name:'Antigua and Barbuda', continent: 'North America', type: 'country', data: ''},
      {location_name:'Aruba', continent: 'North America', type: 'country', data: ''},
      {location_name:'Bahamas', continent: 'North America', type: 'country', data: ''},
      {location_name:'Barbados', continent: 'North America', type: 'country', data: ''},
      {location_name:'Belize', continent: 'North America', type: 'country', data: ''},
      {location_name:'Bermuda', continent: 'North America', type: 'country', data: ''},
      {location_name:'Bonaire, Sint Eustatius and Saba', continent: 'North America', type: 'country', data: ''},
      {location_name:'British Virgin Islands', continent: 'North America', type: 'country', data: ''},
      {location_name:'Canada', continent: 'North America', type: 'country', data: ''},
      {location_name:'Cayman Islands', continent: 'North America', type: 'country', data: ''},
      {location_name:'Costa Rica', continent: 'North America', type: 'country', data: ''},
      {location_name:'Cuba', continent: 'North America', type: 'country', data: ''},
      {location_name:'Curacao', continent: 'North America', type: 'country', data: ''},
      {location_name:'Dominica', continent: 'North America', type: 'country', data: ''},
      {location_name:'Dominican Republic', continent: 'North America', type: 'country', data: ''},
      {location_name:'El Salvador', continent: 'North America', type: 'country', data: ''},
      {location_name:'Greenland', continent: 'North America', type: 'country', data: ''},
      {location_name:'Grenada', continent: 'North America', type: 'country', data: ''},
      {location_name:'Guadeloupe', continent: 'North America', type: 'country', data: ''},
      {location_name:'Guatemala', continent: 'North America', type: 'country', data: ''},
      {location_name:'Haiti', continent: 'North America', type: 'country', data: ''},
      {location_name:'Honduras', continent: 'North America', type: 'country', data: ''},
      {location_name:'Jamaica', continent: 'North America', type: 'country', data: ''},
      {location_name:'Martinique', continent: 'North America', type: 'country', data: ''},
      {location_name:'Mexico', continent: 'North America', type: 'country', data: ''},
      {location_name:'Montserrat', continent: 'North America', type: 'country', data: ''},
      {location_name:'Nicaragua', continent: 'North America', type: 'country', data: ''},
      {location_name:'Panama', continent: 'North America', type: 'country', data: ''},
      {location_name:'Puerto Rico', continent: 'North America', type: 'country', data: ''},
      {location_name:'Saint Barthelemy', continent: 'North America', type: 'country', data: ''},
      {location_name:'Saint Kitts and Nevis', continent: 'North America', type: 'country', data: ''},
      {location_name:'Saint Lucia', continent: 'North America', type: 'country', data: ''},
      {location_name:'Saint Martin', continent: 'North America', type: 'country', data: ''},
      {location_name:'Saint Pierre and Miquelon', continent: 'North America', type: 'country', data: ''},
      {location_name:'Saint Vincent and the Grenadines', continent: 'North America', type: 'country', data: ''},
      {location_name:'Sint Maarten', continent: 'North America', type: 'country', data: ''},
      {location_name:'Trinidad and Tobago', continent: 'North America', type: 'country', data: ''},
      {location_name:'Turks and Caicos Islands', continent: 'North America', type: 'country', data: ''},
      {location_name:'United States', continent: 'North America', type: 'country', data: ''},
      {location_name:'US Virgin Islands', continent: 'North America', type: 'country', data: ''},

      {location_name:'Argentina', continent: 'South America', type: 'country', data: ''},
      {location_name:'Bolivia', continent: 'South America', type: 'country', data: ''},
      {location_name:'Brazil', continent: 'South America', type: 'country', data: ''},
      {location_name:'Chile', continent: 'South America', type: 'country', data: ''},
      {location_name:'Colombia', continent: 'South America', type: 'country', data: ''},
      {location_name:'Ecuador', continent: 'South America', type: 'country', data: ''},
      {location_name:'Falkland Islands', continent: 'South America', type: 'country', data: ''},
      {location_name:'French Guiana', continent: 'South America', type: 'country', data: ''},
      {location_name:'Guyana', continent: 'South America', type: 'country', data: ''},
      {location_name:'Paraguay', continent: 'South America', type: 'country', data: ''},
      {location_name:'Peru', continent: 'South America', type: 'country', data: ''},
      {location_name:'South Georgia and South Sandwich Islands', continent: 'South America', type: 'country', data: ''},
      {location_name:'Suriname', continent: 'South America', type: 'country', data: ''},
      {location_name:'Uruguay', continent: 'South America', type: 'country', data: ''},
      {location_name:'Venezuela', continent: 'South America', type: 'country', data: ''},

      {location_name:'Algeria', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Angola', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Benin', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Botswana', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Bouvet Island', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Burkina Faso', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Burundi', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Cameroon', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Cape Verde', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Central African Republic', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Chad', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Comoros', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Cote d\'Ivoire', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Democratic Republic of Congo', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Djibouti', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Egypt', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Equatorial Guinea', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Eritrea', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Ethiopia', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Gabon', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Gambia', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Ghana', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Glorioso Islands', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Guinea', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Guinea-Bissau', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Juan De Nova Island', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Kenya', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Lesotho', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Liberia', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Libya', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Madagascar', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Malawi', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Mali', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Mauritania', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Mauritius', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Mayotte', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Morocco', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Mozambique', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Namibia', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Niger', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Nigeria', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Republic of Congo', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Reunion', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Rwanda', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Saint Helena', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Sao Tome and Principe', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Senegal', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Seychelles', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Sierra Leone', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Somalia', continent: 'Africa', type: 'country', data: ''},
      {location_name:'South Africa', continent: 'Africa', type: 'country', data: ''},
      {location_name:'South Sudan', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Sudan', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Swaziland', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Tanzania', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Togo', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Tunisia', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Uganda', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Western Sahara', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Zambia', continent: 'Africa', type: 'country', data: ''},
      {location_name:'Zimbabwe', continent: 'Africa', type: 'country', data: ''},

      {location_name:'Afghanistan', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Bahrain', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Bangladesh', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Bhutan', continent: 'Asia', type: 'country', data: ''},
      {location_name:'British Indian Ocean Territory', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Brunei Darussalam', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Cambodia', continent: 'Asia', type: 'country', data: ''},
      {location_name:'China', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Hong Kong', continent: 'Asia', type: 'country', data: ''},
      {location_name:'India', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Indonesia', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Iran', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Iraq', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Israel', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Japan', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Jordan', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Kazakhstan', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Kuwait', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Kyrgyzstan', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Lao People\'s Democratic Republic', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Lebanon', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Macau', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Malaysia', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Maldives', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Mongolia', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Myanmar', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Nepal', continent: 'Asia', type: 'country', data: ''},
      {location_name:'North Korea', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Oman', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Pakistan', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Palestinian Territories', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Philippines', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Qatar', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Saudi Arabia', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Singapore', continent: 'Asia', type: 'country', data: ''},
      {location_name:'South Korea', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Sri Lanka', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Syria', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Taiwan', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Tajikistan', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Thailand', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Timor-Leste', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Turkmenistan', continent: 'Asia', type: 'country', data: ''},
      {location_name:'United Arab Emirates', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Uzbekistan', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Vietnam', continent: 'Asia', type: 'country', data: ''},
      {location_name:'Yemen', continent: 'Asia', type: 'country', data: ''},

      {location_name:'American Samoa', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Australia', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Baker Island', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Christmas Island', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Cocos (Keeling) Islands', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Cook Islands', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Federated States of Micronesia', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Fiji', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'French Polynesia', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'French Southern and Antarctic Lands', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Guam', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Heard Island and McDonald Islands', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Howland Island', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Jarvis Island', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Johnston Atoll', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Kiribati', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Marshall Islands', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Midway Islands', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Nauru', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'New Caledonia', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'New Zealand', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Niue', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Norfolk Island', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Northern Mariana Islands', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Palau', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Papua New Guinea', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Pitcairn Islands', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Samoa', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Solomon Islands', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Timor-Leste', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Tokelau', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Tonga', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Tuvalu', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Vanuata', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Wake Island', continent: 'Oceania', type: 'country', data: ''},
      {location_name:'Wallis and Futuna', continent: 'Oceania', type: 'country', data: ''},

      {location_name:'Alaska', continent: null, type: 'state', data: ''},
      {location_name:'Alabama', continent: null, type: 'state', data: ''},
      {location_name:'Arkansas', continent: null, type: 'state', data: ''},
      {location_name:'Arizona', continent: null, type: 'state', data: ''},
      {location_name:'California', continent: null, type: 'state', data: ''},
      {location_name:'Colorado', continent: null, type: 'state', data: ''},
      {location_name:'Connecticut', continent: null, type: 'state', data: ''},
      {location_name:'Delaware', continent: null, type: 'state', data: ''},
      {location_name:'Florida', continent: null, type: 'state', data: ''},
      {location_name:'Georgia', continent: null, type: 'state', data: ''},
      {location_name:'Hawaii', continent: null, type: 'state', data: ''},
      {location_name:'Iowa', continent: null, type: 'state', data: ''},
      {location_name:'Idaho', continent: null, type: 'state', data: ''},
      {location_name:'Illinois', continent: null, type: 'state', data: ''},
      {location_name:'Indiana', continent: null, type: 'state', data: ''},
      {location_name:'Kansas', continent: null, type: 'state', data: ''},
      {location_name:'Kentucky', continent: null, type: 'state', data: ''},
      {location_name:'Louisiana', continent: null, type: 'state', data: ''},
      {location_name:'Massachusetts', continent: null, type: 'state', data: ''},
      {location_name:'Maryland', continent: null, type: 'state', data: ''},
      {location_name:'Maine', continent: null, type: 'state', data: ''},
      {location_name:'Michigan', continent: null, type: 'state', data: ''},
      {location_name:'Minnesota', continent: null, type: 'state', data: ''},
      {location_name:'Missouri', continent: null, type: 'state', data: ''},
      {location_name:'Mississippi', continent: null, type: 'state', data: ''},
      {location_name:'Montana', continent: null, type: 'state', data: ''},
      {location_name:'Nebraska', continent: null, type: 'state', data: ''},
      {location_name:'Nevada', continent: null, type: 'state', data: ''},
      {location_name:'New Hampshire', continent: null, type: 'state', data: ''},
      {location_name:'New Jersey', continent: null, type: 'state', data: ''},
      {location_name:'New Mexico', continent: null, type: 'state', data: ''},
      {location_name:'New York', continent: null, type: 'state', data: ''},
      {location_name:'North Carolina', continent: null, type: 'state', data: ''},
      {location_name:'North Dakota', continent: null, type: 'state', data: ''},
      {location_name:'Ohio', continent: null, type: 'state', data: ''},
      {location_name:'Oklahoma', continent: null, type: 'state', data: ''},
      {location_name:'Oregon', continent: null, type: 'state', data: ''},
      {location_name:'Pennsylvania', continent: null, type: 'state', data: ''},
      {location_name:'Rhode Island', continent: null, type: 'state', data: ''},
      {location_name:'South Carolina', continent: null, type: 'state', data: ''},
      {location_name:'South Dakota', continent: null, type: 'state', data: ''},
      {location_name:'Tennessee', continent: null, type: 'state', data: ''},
      {location_name:'Texas', continent: null, type: 'state', data: ''},
      {location_name:'Utah', continent: null, type: 'state', data: ''},
      {location_name:'Virginia', continent: null, type: 'state', data: ''},
      {location_name:'Vermont', continent: null, type: 'state', data: ''},
      {location_name:'Washington', continent: null, type: 'state', data: ''},
      {location_name:'Wisconsin', continent: null, type: 'state', data: ''},
      {location_name:'West Virginia', continent: null, type: 'state', data: ''},
      {location_name:'Wyoming', continent: null, type: 'state', data: ''},

      ]);
    });
};
